### PR TITLE
Fix Spotify API

### PR DESCRIPTION
**Pull request by sonictruth**
I fixed the Spotify api

### CODE REVIEW

**Comment by nazar-pc** [comment]
From what I remember `$duration` should be in seconds, also since we'll have seconds directly `if (count($duration) == 2) {` block and its `else` part are not necessary.
Can you fix this?

Otherwise LGTM, nice to see that Spotify have convenient API for this finally, did you test it yourself?

**Comment by sonictruth** [comment]
Hi,
I fixed the duration. I did test the script and it works. VK api still works :+1: .

**Comment by nazar-pc** [comment]
Awesome, thanks man!

**Comment by sonictruth** [comment]
Thank you also... Very useful script :notes:

**Pull request merged**
